  [build]
 publish = "dist" # Директория с вашим React-приложением
   functions = "netlify/functions"
[[redirects]]
   from = "/data/get" 
   to = "/.netlify/functions/server" 
   status = 200 
   force = true
  

